import Head from 'next/head'
import dynamic from 'next/dynamic';
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';


import Home from "./home"


import Errorpage from "./_error"

export default dynamic(() => Promise.resolve(Index), { ssr: false });
function Index() {
  return (
    <>
      <Head>
        <title>FRAME ADMIN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Router>
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="*" element={<Errorpage />} />
        <Route path="/404" element={<Errorpage />} />
      </Routes>
    </Router>
      
    </>
  )
}
