import Head from 'next/head'
import dynamic from 'next/dynamic';
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';


import Login from "./login"
import Home from "./home"
import Blog from "./blog"
import Contact from "./contact"
import Data from "./data"
import Order from "./order"
import Upload from "./upload"
import Comment from "./comment"



import Errorpage from "./_error"

export default dynamic(() => Promise.resolve(Index), { ssr: false });
function Index() {
  return (
    <>
      <Head>
        <title>FRAME ADMIN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Router>
      <Routes>
        <Route path="/" element={<Login />} />
        <Route path="/home" element={<Home />} />
        <Route path="/blog" element={<Blog />} />
        <Route path="/contact" element={<Contact />} />
        <Route path="/data" element={<Data />} />
        <Route path="/order" element={<Order />} />
        <Route path="/upload" element={<Upload />} />
        <Route path="/comment" element={<Comment />} />




        <Route path="*" element={<Errorpage />} />
        <Route path="/404" element={<Errorpage />} />
      </Routes>
    </Router>
      
    </>
  )
}
